dataverse bridge plugin implementation for EASY
DANS-KNAW/dataverse-bridge-plugin-easy pull request #1
Opened 2018-09-19 09:30 UTC by ekoi

2018-11-14 14:02 UTC, PaulBoon commented
We should add a LICENSE file with the Apache 2.0 license.

2018-11-14 15:08 UTC, PaulBoon commented
Overall it looks fine!

2018-11-14 15:09 UTC, PaulBoon requested changes
Pleas explain or fix those issues.

2018-11-14 15:09 UTC, PaulBoon commented on src/test/java/nl/knaw/dans/bridge/plugin/dar/easy/EasyTransformerTest.java
> +        URL metadataUrl = new File("/Users/akmi/git/bridge/bridge-plugin-easy/src/test/resources/json/hdl-101204-hkdsa.json").toURI().toURL();
This makes my test fail, I am don't have this directory. 
Please make it use a relative path somehow.

2018-11-14 15:09 UTC, PaulBoon commented on src/test/java/nl/knaw/dans/bridge/plugin/dar/easy/EasyTransformerTest.java
> +        destinationDar = new DestinationDar(new IRI("http://deasy.dans.knaw.nl/sword2/collection/1"), "ekoi", "secret", "DANS");
This will only work if the 'deasy' VM is running?

2018-11-14 15:09 UTC, PaulBoon commented on README.md
> +Thi is the implementation of a [bridge-plugin](https://github.com/DANS-KNAW/dataverse-bridge-plugin-lib) for ingesting data to the [EASY](https://easy.dans.knaw.nl/ui/home) archive.
Type: should be 'This' instead of 'Thi'.

2018-11-14 15:09 UTC, PaulBoon commented on README.md
> +This plugin transforms the dataverse metadata file in DDI format into the required metadata files by EASY; ‘dataset.xml’ and ‘files.xml’.
It's not using DDI anymore, it's using JSON isn't it?

2018-11-14 15:09 UTC, PaulBoon commented on src/main/resources/easy.json
> +{
This one ends up in the dist folder, but there it is unversioned an not in .gitignore. 
Maybe we should put the whole dist folder in the .gitignore to get rid of 'complaints' from the IDE.

2018-11-20 08:58 UTC, ekoi commented on src/test/java/nl/knaw/dans/bridge/plugin/dar/easy/EasyTransformerTest.java
> +        URL metadataUrl = new File("/Users/akmi/git/bridge/bridge-plugin-easy/src/test/resources/json/hdl-101204-hkdsa.json").toURI().toURL();
Fixed!

2018-11-20 08:58 UTC, ekoi commented on README.md
> +Thi is the implementation of a [bridge-plugin](https://github.com/DANS-KNAW/dataverse-bridge-plugin-lib) for ingesting data to the [EASY](https://easy.dans.knaw.nl/ui/home) archive.
Fixed.

2018-11-20 08:59 UTC, ekoi commented on src/main/resources/easy.json
> +{
👍 
I added dist in the .gitignore

2018-11-20 14:58 UTC, merged